version: '3.4'

services:
  apibackendwebapi:
    image: apibackendwebapi
    build:
      context: .
      dockerfile: src/ApiBackend.WebAPi/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
